name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov=roll_sim --cov-report xml:cov.xml --junitxml=res.xml
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            res.xml

      - name: Coverage report
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path: cov.xml
          minimum_coverage: 66