name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -e .

      - name: Run tests with coverage
        run: |
          pytest > coverage_report.txt

      - name: Display test results and coverage
        run: |
          cat coverage_report.txt